name: first_workflow

on:
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Download node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create build
        run: npm run build

      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist
          retention-days: 7
      
      - name: install vercel
        run: npm i -g vercel
      
      # - name: deploy project to vercel
      #   run: vercel --prod --yes --token=${{secrets.VERCEL_SECRET}}

      - name: directly deploy project to vercel
        run: vercel deploy dist --prod --yes --token=${{secrets.VERCEL_SECRET}}